version: '2'

networks:
  app-tier:
    driver: bridge

services:
  kafka_b:
    image: 'bitnami/kafka:latest'
    hostname: kafka_b
    networks:
      - app-tier
    ports:
      - '9092:9092' # the internal, client one can still be used within the docker network
      - '9094:9094'
      # - "9101:9092"
      # - "9102:9093"
      # - "9103:9094"
    expose:
     - '9093'
    # volumes:
    #   - "kafka_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_ENABLE_KRAFT=yes
      # - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,EXTERNAL://kafka:9094
      # - KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      # - KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      # - KAFKA_BROKER_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka_b:9093
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@host.docker.internal:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    networks:
      - app-tier
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      LOGGING_LEVEL_ROOT: 'DEBUG'
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    # volumes:
    #   - /c/tools/kafka/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  flask-recommendation-server:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: flask-server
    networks:
      - app-tier
    ports:
      - '5000:5000'

volumes:
  kafka_data:
    driver: local